"""Dados de seed embutidos (gerados de app/data/*.json).

NÃO edite à mão — rode scripts/build_assets.py após mudar os .json.
Embutidos para o bundle serverless da Vercel (sem includeFiles).
"""

PLAYERS = ['Kylian Mbappé',
 'Erling Haaland',
 'Vinícius Júnior',
 'Endrick',
 'Rodrygo',
 'Harry Kane',
 'Lautaro Martínez',
 'Julián Álvarez',
 'Lionel Messi',
 'Cristiano Ronaldo',
 'Rafael Leão',
 'Lamine Yamal',
 'Florian Wirtz',
 'Jamal Musiala',
 'Bukayo Saka',
 'Victor Osimhen',
 'Mohamed Salah',
 'Cody Gakpo',
 'Olivier Giroud',
 'Antoine Griezmann']

FIXTURES = [{'stage': 'grupos',
  'round': 3,
  'home_team': 'Suíça',
  'away_team': 'Canadá',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-24T19:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Bósnia e Herzegovina',
  'away_team': 'Catar',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-24T19:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Escócia',
  'away_team': 'Brasil',
  'teams_decided': True,
  'is_brazil': True,
  'kickoff_at': '2026-06-24T22:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Marrocos',
  'away_team': 'Haiti',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-24T22:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Tchéquia',
  'away_team': 'México',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T01:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'África do Sul',
  'away_team': 'Coreia do Sul',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T01:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Equador',
  'away_team': 'Alemanha',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T20:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Curaçao',
  'away_team': 'Costa do Marfim',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T20:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Japão',
  'away_team': 'Suécia',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T23:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Tunísia',
  'away_team': 'Países Baixos',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-25T23:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Turquia',
  'away_team': 'Estados Unidos',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-26T02:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Paraguai',
  'away_team': 'Austrália',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-26T02:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Noruega',
  'away_team': 'França',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-26T19:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Senegal',
  'away_team': 'Iraque',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-26T19:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Cabo Verde',
  'away_team': 'Arábia Saudita',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T00:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Uruguai',
  'away_team': 'Espanha',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T00:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Egito',
  'away_team': 'Irã',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T03:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Nova Zelândia',
  'away_team': 'Bélgica',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T03:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Panamá',
  'away_team': 'Inglaterra',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T21:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Croácia',
  'away_team': 'Gana',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T21:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Colômbia',
  'away_team': 'Portugal',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T23:30:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'RD Congo',
  'away_team': 'Uzbequistão',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-27T23:30:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Argélia',
  'away_team': 'Áustria',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-28T02:00:00+00:00'},
 {'stage': 'grupos',
  'round': 3,
  'home_team': 'Jordânia',
  'away_team': 'Argentina',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-28T02:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'África do Sul',
  'away_team': 'Canadá',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-28T19:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Brasil',
  'away_team': 'Japão',
  'teams_decided': True,
  'is_brazil': True,
  'kickoff_at': '2026-06-29T17:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Alemanha',
  'away_team': 'Paraguai',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-29T20:30:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Países Baixos',
  'away_team': 'Marrocos',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-30T01:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Costa do Marfim',
  'away_team': 'Noruega',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-30T17:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'França',
  'away_team': 'Suécia',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-06-30T21:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'México',
  'away_team': 'Equador',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-01T01:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Inglaterra',
  'away_team': 'RD Congo',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-01T16:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Bélgica',
  'away_team': 'Senegal',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-01T20:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Estados Unidos',
  'away_team': 'Bósnia e Herzegovina',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-02T00:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Espanha',
  'away_team': 'Áustria',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-02T19:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Portugal',
  'away_team': 'Croácia',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-02T23:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Suíça',
  'away_team': 'Argélia',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-03T03:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Austrália',
  'away_team': 'Egito',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-03T18:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Argentina',
  'away_team': 'Cabo Verde',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-03T22:00:00+00:00'},
 {'stage': '16avos',
  'round': None,
  'home_team': 'Colômbia',
  'away_team': 'Gana',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-04T01:30:00+00:00'},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Canadá',
  'away_team': 'Marrocos',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-04T17:00:00+00:00',
  'bracket_pos': 1},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Paraguai',
  'away_team': 'França',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-04T21:00:00+00:00',
  'bracket_pos': 2},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Brasil',
  'away_team': 'Noruega',
  'teams_decided': True,
  'is_brazil': True,
  'kickoff_at': '2026-07-05T20:00:00+00:00',
  'bracket_pos': 3},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'México',
  'away_team': 'Inglaterra',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-06T00:00:00+00:00',
  'bracket_pos': 4},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Portugal',
  'away_team': 'Espanha',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-06T19:00:00+00:00',
  'bracket_pos': 5},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Estados Unidos',
  'away_team': 'Bélgica',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-07T00:00:00+00:00',
  'bracket_pos': 6},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Argentina',
  'away_team': 'Egito',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-07T16:00:00+00:00',
  'bracket_pos': 7},
 {'stage': 'oitavas',
  'round': None,
  'home_team': 'Suíça',
  'away_team': 'Colômbia',
  'teams_decided': True,
  'is_brazil': False,
  'kickoff_at': '2026-07-07T20:00:00+00:00',
  'bracket_pos': 8},
 {'stage': 'quartas',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-10T19:00:00+00:00',
  'bracket_pos': 1},
 {'stage': 'quartas',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-10T23:00:00+00:00',
  'bracket_pos': 2},
 {'stage': 'quartas',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-11T19:00:00+00:00',
  'bracket_pos': 3},
 {'stage': 'quartas',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-11T23:00:00+00:00',
  'bracket_pos': 4},
 {'stage': 'semi',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-14T19:00:00+00:00',
  'bracket_pos': 1},
 {'stage': 'semi',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-15T19:00:00+00:00',
  'bracket_pos': 2},
 {'stage': 'terceiro',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-18T18:00:00+00:00',
  'bracket_pos': None},
 {'stage': 'final',
  'round': None,
  'home_team': 'A definir',
  'away_team': 'A definir',
  'teams_decided': False,
  'is_brazil': False,
  'kickoff_at': '2026-07-19T19:00:00+00:00',
  'bracket_pos': 1}]
